### PR TITLE
Addl modules

### PR DESCRIPTION
**Pull request by mrallen1**
Problems to solve:
* jsx has been deprecated for years
* need secrets manager client base

Solutions:
* use jsone for JSON encoding/decoding
* add secrets manager to the list of modules to generate

### CODE REVIEW

**Comment by jfacorro** [comment]
@mrallen1 I'm going over the open PRs and I was wondering what makes you say that "jsx has been deprecated for years". It looks like it's [still being maintained](https://github.com/talentdeficit/jsx) and there are quite a few [recent releases](https://hex.pm/packages/jsx) for it in hex.pm.

**Comment by mrallen1** [comment]
It had been the case for a long time. In any case, I just prefer jsone 🤷

**Comment by jfacorro** [comment]
I can add support for the `Secrets Manager` API in a new PR. Would you be willing to keep `jsx` since that is what is currently being used and seems to work? If so, can I close this PR? 😄 🙏

**Comment by mrallen1** [comment]
I guess so. Still prefer jsone though.

**Comment by jfacorro** [comment]
Secrets Manager API is now added #18. 😄 

I will close this PR and we can discuss migrating to `jsone` in #19.

**Pull request closed without merging**
